# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d24ff519ec5ab3c03f2038f045b0947afd7af9ed1f85455c5d0c06d49e03b879a37258f0a142667ea27a20a2c4984e71c720e118402bebf505dc10d583e6ae74

test:
  secret_key_base: ab54d71a427422945bf9c93ac1dda28d7d0fdf607e97a5cd6d2fe85ac090eecbc6d95a34fdb854f3e9e9ee6dfa8591eba75dd6b0229165f019261692e1c95a04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
